### ISSUE TITLE
Debugging APK with Symbols

### ISSUE THREAD

**Issue by Honeybunch** [adelphes/android-dev-ext#107]
My workflow with Android involves a mostly-native and very polyglot code-base. Gradle is not involved, the build system is 100% CMake and Cargo. I end up with a very unconventional source tree as I wrangle C, C++, Java and Rust into an APK. Android Studio is particularly bad at letting me debug any Rust with its APK Debugging feature but it does let me attach symbols from a known symbol root. This extension doesn't seem to have any equivalent feature. Am I correct in assuming that this extension is mostly relying on a standardized source tree for resolving symbols? Is there any way that I could provide it a symbolized native lib instead?

**Comment by adelphes** [comment]
Your assumptions are right: the Android extension is used for fairly simple android development and assumes a standardized layout for source files. It also doesn't support any kind of native debugging (it just hooks into JDWP to provide Java debug capabilities.)
