### ISSUE TITLE
Is development stopped on this extension?

### ISSUE THREAD

**Issue by akash07k** [adelphes/android-dev-ext#135]
I want to know that is development stopped on this extension?
  Asking since last update is more than 2 years ago.

**Comment by adelphes** [comment]
Hi @akash07k - it's a good question.
It's true that no new functionality has been added for a while, but I believe the debugger still works in the latest version of VSCode and I'm happy to accept PRs for any bug fixes or new features people want to add.

**Comment by akash07k** [comment]
Ok, so does the last release work well with latest versions of VS Code?

Also, will we get code autocompletion support?

**Comment by adelphes** [comment]
Yes, the current release of the Android extension still works with the latest version of VSCode.
It includes:
- Debugging support (breakpoints, stepping, evaluate local variables, etc)
- View logcat
- Java code-completion

> Also, will we get code autocompletion support?
Java code-completion for standard Android libraries should work. Pressing ctrl + space should bring up relevant identifiers if they don't appear automatically.
