### ISSUE TITLE
Unable to find localabstract name of cordova app

### ISSUE THREAD

**Issue by nizampatnamnagaraju** [adelphes/android-dev-ext#20]
while i click on run on android device it shows
App successfully launched
Attaching to android
Unable to find localabstract name of cordova app

**Comment by adelphes** [comment]
The Android debug adaptor is for Android Apps coded in Java. 
If you're using cordova, you might want to try the [Microsoft cordova plugin](https://github.com/Microsoft/vscode-cordova) instead.
