### ISSUE TITLE
Automatically build

### ISSUE THREAD

**Issue by declanmarks** [adelphes/android-dev-ext#21]
Would it be possible to add the feature to automatically build the apk. It is very annoying that I have to go into the console to build and the run the app.

**Comment by dave-plutoflume** [comment]
VSCode supports the creation of [custom build tasks](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks) - you could always create one to run the command to build your app.

**Comment by adelphes** [comment]
You can achieve this easily by creating a build task and assigning it as a pre-launch action.

Create a **.vscode/tasks.json** with the following content:
```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "${workspaceFolder}/gradlew assembleDebug",
            "problemMatcher": {
                "fileLocation": ["absolute"],
                "owner": "gradle",
                "pattern": {
                    "regexp": "^([we]): ([^:]+): \\((\\d+),\\s*(\\d+)\\):\\s+(.+)",
                    "file": 2,
                    "line": 3,
                    "column": 4,
                    "severity": 1,
                    "message": 5
                }
            }
        }
    ]
}
```

Add the following entry to your **launch.json** Android debug configuration:
```
"preLaunchTask": "build"
```
