### ISSUE TITLE
Debug starts but dies on splash activity

### ISSUE THREAD

**Issue by nahuelhds** [adelphes/android-dev-ext#22]
Hi! I'm very interested in using your debugger. Look quite good. I've successfuly connected to ADB, setup the apk file through the launch.json file and so. The thing is that when I press F5 I have the following output in the cosole:

```
Checking buildSearching for devices...
Found 1
deviceDeploying current build...
Installing...
Launching com.aviron.pasajeros/.splash.SplashActivity on device 192.168.189.101:5555 [API:16]
Device disconnected
```

Those lines are shown alltogether but that's not an issue right now. The thing is that after launching the app the debugging process dies and so the app.

Maybe I'm doing something wrong.

My context is:
- Windows 10 64 bits.
- AMD processor
- Running with Genymotion

Thanks in advance

**Comment by dave-plutoflume** [comment]
There are a number of reasons why the debugger would immediately disconnect - the most common is when an APK supporting a newer SDK version is run on an older SDK emulator.

I would need to see the output from Logcat during the App launch to get more information about why the debugger is disconnecting.

**Comment by SaguruHakuba** [comment]
This project is dead? No one uses that?

**Comment by nahuelhds** [comment]
Use Android Studio. It has become so much better since then

**Comment by SaguruHakuba** [comment]
Oh no..... visual studio code way much better than Android Studio.

**Comment by adelphes** [comment]
This is another issue with the app terminating on an emulator. Logcat should show the reason for the debugger connection terminating.

Closing until more information is available.
