### ISSUE TITLE
AndroidViewLogcat 

### ISSUE THREAD

**Issue by kenkit** [adelphes/android-dev-ext#23]
Is it possible to make this option only log the current apk in the configuration ?
I mean it should do something like 
`adb logcat | findstr in.asdjsad.myremote.app`

or maybe add another Android view to display on the current apk specified in the config file

**Comment by dave-plutoflume** [comment]
You can always set the filter to your APK package name, but I will look at adding an additional option to limit it to the installing APK

**Comment by adelphes** [comment]
You are able to filter the logcat output using a regular expression - you can just sent it to your package name if you want to filter to your apk.

**Comment by kenkit** [comment]
I see, thank you
