### ISSUE TITLE
[Feature Request] Debugger Support - Kotlin

### ISSUE THREAD

**Issue by ahoefling** [adelphes/android-dev-ext#25]
First off this is a really cool extension and I am now able to use VS Code to run and deploy my android apps. 

We are using kotlin for our Android project and it appears there isn't debugger support for kotlin in VS Code. According to #19 this extension hooks into the JDWP which is the protocol for debugging java classes. 

**Feature Request**
Do you plan to support kotlin debugging and what is your timeline for that if you do?

**Comment by adelphes** [comment]
I agree that adding support for Kotlin debugging in this extension would be really useful, but due to time-restrictions, I have no future plans to implement it.

This is an open-source project and I would welcome any PRs that go towards supporting it.

**Comment by adelphes** [comment]
It appears that Kotlin (and its runtime) are fully compatible with JDWP - I've now published v0.5.0 of the debugger extension to support Kotlin (.kt) files. Let me know if there are any issues with it.
