### ISSUE TITLE
Unable to view Logcat

### ISSUE THREAD

**Issue by timur-almaev** [adelphes/android-dev-ext#49]
Hi, thanks a lot for the extension, it's great to have some alternative to Android Studio. I've just installed it on VS Code 1.29.1, but when I try to open logcat I get the following error:

`command 'android-dev-ext.view_logcat' not found`

Does this look like a bug or is it something I'm missing?

Cheers!

**Comment by gtino** [comment]
Same here, just installed in VS Code 1.30.0 and I get the same exact error. 
I have adb logcat installed and works fine from command line.

**Comment by adelphes** [comment]
Fixed in 0.6.2

**Comment by timur-almaev** [comment]
Thanks!
