### ISSUE TITLE
Build apk

### ISSUE THREAD

**Issue by senpl** [adelphes/android-dev-ext#51]
Building apk is already done for flutter/dart vs code extension. So it could be probably copied from there or done similar. Of course this could be optional. But most users probably want to build app before debugging.

**Comment by adelphes** [comment]
I agree that most people want the app built before debugging - the problem is, there are lots of different ways Android apps get built, depending on the library/framework being used. Trying to get the debugger extension to work out which method is correct is difficult - and if another extension already performs the build, I wouldn't want to duplicate it.

If you always want the APK to be built before debugging starts, you should be able to create a `preLaunchTask` entry in the Android Debug configuration and run the command used to build the app.

**Comment by senpl** [comment]
`If you use gradle (or Android Studio), you can build your app from the command-line using ./gradlew assembleDebug` . Assuming that most android project use gradle why command `./gradlew assembleDebug` could not be run by extetnsion ??? If it will not be gradle it could do nothing.If it is build should start.

**Comment by adelphes** [comment]
> Assuming that most android project use gradle

...but not all projects do.

> If it will not be gradle it could do nothing.

How do we detect the difference between a misconfigured gradle and one that doesn't use gradle? This sounds like a simple task, but in reality `gradle` is a complex build system that can be used in lots of different ways.

This extension is designed as a debugger extension - it's really not designed to build the app. As I mentioned, if you always want the app to be built before launching a debug session, it really is as simple as adding a `preLaunchTask` like this.

### .vscode/launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "android",
            "name": "Android Debug",
            "request": "launch",
            "appSrcRoot": "${workspaceRoot}/app/src/main",
            "apkFile": "${workspaceRoot}/app/build/outputs/apk/app-debug.apk",
            "adbPort": 5037,
            "preLaunchTask": "run gradle",
            "staleBuild": "stop",
        }
    ]
}
```


### .vscode/tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "run gradle",
            "type": "shell",
            "command": "${workspaceFolder}/gradlew",
            "args": ["assembleDebug"]
        }
    ]
}
```

This flexibility in vscode allows the app to built using any command designed into the framework being used.

**Comment by senpl** [comment]
Ok. Maybe adding information how to set up run with gradle build task to project wiki is a way to go. To me if gradlew is found then it should be run (or be optional to run). But If your experience show then most users want to configure it themselves then You might be right.

**Comment by j-rewerts** [comment]
It may be worth adding that tasks.json to the readme?

**Comment by adelphes** [comment]
Info about adding a prelaunch task has been added to the README.
