### ISSUE TITLE
How to debug native applications?

### ISSUE THREAD

**Issue by fabiopolimeni** [adelphes/android-dev-ext#52]
Hi guys,

I was wondering whether this plugin is capable of debugging native applications through VS.

I have an app and I generate the manifest and the whole directory tree through a python script (no gradle, purely javac). This means that my source files, the *.c files, are kept separated from this tree. Now, when I hit the debug button, the application correctly boots up on my device, but I don't seem to be able to hit the breakpoints in the native code, in fact, they grey out as soon as the debugger starts. Moreover, and I don't know whether this is relevant or not, on the screen of my mobile phone a popup shows up saying the application is waiting for the debugger to be attached. After a few moments it goes away, so I guess, the debugger is properly attached.

Any suggestion?

**Comment by adelphes** [comment]
Hi @fabiopolimeni 
I'm afraid the debugger only works with java (and kotlin) files because it uses the Java runtime to manage breakpoints, etc. If you are running native compiled code, the extension won't recognise any breakpoints.

Android does support native debugging via gdb, so you might be able to use a different VSCode extension supporting gdb and attach to the (remote) process after it has launched on the device.

**Comment by fabiopolimeni** [comment]
I see, thanks @adelphes 

About gdb and Android NDK, unfortunately it doesn't seem to be straight forward, because gdb needs gdbserver running on the device, and to do that the phone needs to be rooted, which breaks warranties on the devices (plus in some device, like mine one is a cumbersome operation). So, unless someone has a different solution, gdb/gdbserver doesn't seems to be a trivial solution.

Thanks

**Comment by fabiopolimeni** [comment]
I see, thanks @adelphes
About gdb and Android NDK, unfortunately it doesn't seem to be straight forward, because gdb needs gdbserver running on the device, and to do that the phone needs to be rooted, which breaks warranties on the devices (plus in some device, like mine one is a cumbersome operation). So, unless someone has a different solution, gdb/gdbserver doesn't seems to be a trivial solution.
Thanks

**Comment by mumin16** [comment]
I would welcome any solution to debug native applications :)
