### ISSUE TITLE
Doesn't work with VSCode 1.33

### ISSUE THREAD

**Issue by espositofulvio** [adelphes/android-dev-ext#54]
Updating to VSCode 1.33 broke the ability to set breakpoints, anytime I try the breakpoint comes up grey and hovering on it says that the location is not valid. Reverting my VSCode installation to 1.32.3 made it work again.

**Comment by adelphes** [comment]
@espositofulvio Thanks for reporting. I just tested on VSCode v1.33.1 and the extension seems to set and hit breakpoints with any issues.

Can you provide some additional details for me to look into:
- what OS type + version are you running?
- what version of the android extension do you have installed?
- can you copy and paste the information from the VS code Help -> About dialog.

**Comment by espositofulvio** [comment]
I'm on Windows 10 Professional, the Android extension version is 0.6.2. As I said, I had to revert VSCode to 1.32.3 as I'm using all this at work, but it all started when I updated to 1.33.0. I'll give it a go again with 1.33.1.

**Comment by espositofulvio** [comment]
Just updated and tried, breakpoints are broken again:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by adelphes** [comment]
OK - if it's on Windows, it may the same problem with file path case-sensitivity as #24 - could you try patching the source as shown in the other issue and see if that fixes it.

**Comment by espositofulvio** [comment]
Yep that worked, thanks! I'll close this. I also wonder why the issue didn't come up with VsCode 1.32.3. Anyway, thanks again.
