### ISSUE TITLE
specify Launch-activity in launch.json

### ISSUE THREAD

**Issue by felwolff** [adelphes/android-dev-ext#56]
I don't have a launch activity in the Manifest (and won't add one, because it normally runs as a service). I use an Activity for debugging to launch the App and used to do it in Android Studio with specifying a launch configuration. 
Reading the error output `Launch failed: No valid launch activity found in AndroidManifest.xml or launch.json` indicates I could do the same, but how to I set it? At least the auto-suggestions did not suggest a suitable attribute.

**Comment by hydro0** [comment]
Use `launchActivity` in `launch.json`
