### ISSUE TITLE
pm install -t option

### ISSUE THREAD

**Issue by adrianstephens** [adelphes/android-dev-ext#73]
For our project I had to edit debugMain.js at line 404 to add '-t' to the pm install command. I'm not sure if there are any downsides to always having that flag set, but would it be possible to either add it permanently, or have it as an option in the configuration?

**Comment by adelphes** [comment]
Could you explain what the `-t` option is and add a brief explanation as to why you need it.

I think the `pm` command could be made an option to allow some simple customisation.

**Comment by adrianstephens** [comment]
tbh I need it to debug someone else's android project, but from running pm without arguments I see that the -t flag is "allow test packages". I think a test package is just one with a test flag in the AndroidManifest, and that pm will not install them unless you give it the -t flag.
I don't know the reasons for having the flag, but it was safer for me to modify the js than to mess with the gradle settings!
