### ISSUE TITLE
Attaching debugger to running process

### ISSUE THREAD

**Issue by davystrong** [adelphes/android-dev-ext#77]
Is there any way to attach the debugger to an existing process? Specifically, I'm using flutter and I'd like to attach to a plugin running in my app.

**Comment by adelphes** [comment]
No, this functionality is not in the debugger.
The debugger always launches a new instance of an app with debugging capabilities enabled.

**Comment by adelphes** [comment]
@davystrong I am looking into adding this functionality for the next release.

**Comment by davystrong** [comment]
Ok, great. I finished the project I was working on that needed this but it should be useful in future! Thanks for your help and for developing this plugin.

**Comment by adelphes** [comment]
Fixed in #85
