### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by Lazare-C** [adelphes/android-dev-ext#79]
The APK is not found in a folder on my Ubuntu wsl :/

"Checking build
Launch failed: APK read error. ENOENT: no such file or directory, open '/home/***/Developer/ang03/android/app/build/outputs/apk/app-debug.apk'"

**Comment by adelphes** [comment]
@Lazare-C 
Before I dig further into this (I will need to setup a new Windows environment with Ubuntu WSL) - was the file definitely in that location?

Some gradle configurations place the APK in a different folder with a different name.
