### ISSUE TITLE
--activity-brought-to-front breaks things

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [adelphes/android-dev-ext#82]
To make my app launch properly, I have to remove `'--activity-brought-to-front'` from https://github.com/adelphes/android-dev-ext/blob/8cc31476b3e489f06b39b51893f49d3fc747fab3/src/debugger.js#L88. If I don't, as soon as it's finished waiting for the debugger to attach, the app minimises.

I narrowed down this argument as the culprit by comparing the command Android Studio gave to ADB with the one this extension gave. It seems to have been there since the first commit to this repo.

**Comment by adelphes** [comment]
Thanks!
Support for custom launch arguments will be included in the next release.
