### ISSUE TITLE
Cannot be used in WSL 2 because HOST cannot be overridden

### ISSUE THREAD

**Issue by ThaDaVos** [adelphes/android-dev-ext#95]
It seems the extension is fixed to using `127.0.0.1` as host for the ADB server - but in my case it's running on my windows machine and I need to connect to it by using the `ADB_SERVER_SOCKET` env, which seems not to be used in the extension.

Is there any way to override the host?

**Comment by adelphes** [comment]
Hi @ThaDaVos - thanks for raising the issue.
It is the case that the connection to ADB is currently fixed at `127.0.0.1`.

I can easily update this to look for the ADB_SERVER_SOCKET env variable. From other similarly reported issues, it appears the standard format for this variable is:

```
ADB_SERVER_SOCKET=tcp:<host>:<port>
```

where <host> and <port> are the normal hostname/ip-address and port names for the socket connection.

Can i confirm that this Is what you expect?

**Comment by ThaDaVos** [comment]
That's exactly what I expect yes -> I set that ENV manually to connect the command line ADB to my windows so I can list the devices connected
